language: python

python:
 - "3.6"

install:
  - "pip install -r requirements.txt"

  
 
script: 
  - nosetests --with-coverage --cover-package level-up
  - coverage report
 
after_success:
  - coveralls